#############################################################################
# Makefile for building: SoftPhone
# Generated by qmake (2.01a) (Qt 4.8.7) on: Çar Ara 6 13:50:16 2017
# Project:  SoftPhone.pro
# Template: app
# Command: /usr/lib/x86_64-linux-gnu/qt4/bin/qmake -o Makefile SoftPhone.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtGui -I/usr/include/qt4 -Iusr/lib -Iusr/local/lib -I. -I.
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/x86_64-linux-gnu `pkg-config --libs libpjproject` -lboost_system -lboost_chrono -lboost_thread -ludev -lnetsnmp -lasound -lfftw3 -lQtGui -lQtNetwork -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/lib/x86_64-linux-gnu/qt4/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		SoftPhone.cpp \
		FileFactory.cpp \
		FileItem.cpp \
		Functions.cpp \
		IniFileIterator.cpp \
		IniFileLoader.cpp \
		PttAdapter.cpp \
		PttManager.cpp \
		SnmpStack.cpp \
		TCPCommunicator.cpp \
		TransportAdapter.cpp \
		UDPCommunicator.cpp \
		Utility.cpp \
		WavWriter.cpp \
		Plotter.cpp moc_SoftPhone.cpp \
		moc_Plotter.cpp
OBJECTS       = main.o \
		SoftPhone.o \
		FileFactory.o \
		FileItem.o \
		Functions.o \
		IniFileIterator.o \
		IniFileLoader.o \
		PttAdapter.o \
		PttManager.o \
		SnmpStack.o \
		TCPCommunicator.o \
		TransportAdapter.o \
		UDPCommunicator.o \
		Utility.o \
		WavWriter.o \
		Plotter.o \
		moc_SoftPhone.o \
		moc_Plotter.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		SoftPhone.pro
QMAKE_TARGET  = SoftPhone
DESTDIR       = 
TARGET        = SoftPhone

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_SoftPhone.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: SoftPhone.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/x86_64-linux-gnu/libQtGui.prl \
		/usr/lib/x86_64-linux-gnu/libQtNetwork.prl \
		/usr/lib/x86_64-linux-gnu/libQtCore.prl
	$(QMAKE) -o Makefile SoftPhone.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_phonon.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/shared.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/x86_64-linux-gnu/libQtGui.prl:
/usr/lib/x86_64-linux-gnu/libQtNetwork.prl:
/usr/lib/x86_64-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile SoftPhone.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/SoftPhone1.0.0 || $(MKDIR) .tmp/SoftPhone1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/SoftPhone1.0.0/ && $(COPY_FILE) --parents SoftPhone.h Codecs.h ConfigException.h ed137_rtp.h FileFactory.h FileItem.h FileIteratorInterface.h FileLoaderInterface.h IniFileIterator.h IniFileLoader.h IPttListener.h PttAdapter.h PttManager.h SnmpStack.h TCPCommunicator.h TransportAdapter.h UDPCommunicator.h Utility.h WavWriter.h StaticVariables.h Plotter.h .tmp/SoftPhone1.0.0/ && $(COPY_FILE) --parents main.cpp SoftPhone.cpp FileFactory.cpp FileItem.cpp Functions.cpp IniFileIterator.cpp IniFileLoader.cpp PttAdapter.cpp PttManager.cpp SnmpStack.cpp TCPCommunicator.cpp TransportAdapter.cpp UDPCommunicator.cpp Utility.cpp WavWriter.cpp Plotter.cpp .tmp/SoftPhone1.0.0/ && $(COPY_FILE) --parents SoftPhone.ui .tmp/SoftPhone1.0.0/ && (cd `dirname .tmp/SoftPhone1.0.0` && $(TAR) SoftPhone1.0.0.tar SoftPhone1.0.0 && $(COMPRESS) SoftPhone1.0.0.tar) && $(MOVE) `dirname .tmp/SoftPhone1.0.0`/SoftPhone1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/SoftPhone1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_SoftPhone.cpp moc_Plotter.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_SoftPhone.cpp moc_Plotter.cpp
moc_SoftPhone.cpp: Utility.h \
		SnmpStack.h \
		TransportAdapter.h \
		ed137_rtp.h \
		FileLoaderInterface.h \
		FileIteratorInterface.h \
		FileItem.h \
		ConfigException.h \
		FileFactory.h \
		PttManager.h \
		PttAdapter.h \
		IPttListener.h \
		UDPCommunicator.h \
		TCPCommunicator.h \
		WavWriter.h \
		SoftPhone.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) SoftPhone.h -o moc_SoftPhone.cpp

moc_Plotter.cpp: Plotter.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) Plotter.h -o moc_Plotter.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_SoftPhone.h
compiler_uic_clean:
	-$(DEL_FILE) ui_SoftPhone.h
ui_SoftPhone.h: SoftPhone.ui
	/usr/lib/x86_64-linux-gnu/qt4/bin/uic SoftPhone.ui -o ui_SoftPhone.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp SoftPhone.h \
		Utility.h \
		SnmpStack.h \
		TransportAdapter.h \
		ed137_rtp.h \
		FileLoaderInterface.h \
		FileIteratorInterface.h \
		FileItem.h \
		ConfigException.h \
		FileFactory.h \
		PttManager.h \
		PttAdapter.h \
		IPttListener.h \
		UDPCommunicator.h \
		TCPCommunicator.h \
		WavWriter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

SoftPhone.o: SoftPhone.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o SoftPhone.o SoftPhone.cpp

FileFactory.o: FileFactory.cpp FileFactory.h \
		FileLoaderInterface.h \
		FileIteratorInterface.h \
		FileItem.h \
		ConfigException.h \
		IniFileLoader.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o FileFactory.o FileFactory.cpp

FileItem.o: FileItem.cpp FileItem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o FileItem.o FileItem.cpp

Functions.o: Functions.cpp SoftPhone.h \
		Utility.h \
		SnmpStack.h \
		TransportAdapter.h \
		ed137_rtp.h \
		FileLoaderInterface.h \
		FileIteratorInterface.h \
		FileItem.h \
		ConfigException.h \
		FileFactory.h \
		PttManager.h \
		PttAdapter.h \
		IPttListener.h \
		UDPCommunicator.h \
		TCPCommunicator.h \
		WavWriter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Functions.o Functions.cpp

IniFileIterator.o: IniFileIterator.cpp IniFileIterator.h \
		FileIteratorInterface.h \
		FileItem.h \
		ConfigException.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o IniFileIterator.o IniFileIterator.cpp

IniFileLoader.o: IniFileLoader.cpp IniFileLoader.h \
		FileLoaderInterface.h \
		FileIteratorInterface.h \
		FileItem.h \
		ConfigException.h \
		IniFileIterator.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o IniFileLoader.o IniFileLoader.cpp

PttAdapter.o: PttAdapter.cpp PttAdapter.h \
		IPttListener.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o PttAdapter.o PttAdapter.cpp

PttManager.o: PttManager.cpp PttManager.h \
		Utility.h \
		PttAdapter.h \
		IPttListener.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o PttManager.o PttManager.cpp

SnmpStack.o: SnmpStack.cpp SnmpStack.h \
		StaticVariables.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o SnmpStack.o SnmpStack.cpp

TCPCommunicator.o: TCPCommunicator.cpp TCPCommunicator.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o TCPCommunicator.o TCPCommunicator.cpp

TransportAdapter.o: TransportAdapter.cpp TransportAdapter.h \
		ed137_rtp.h \
		SoftPhone.h \
		Utility.h \
		SnmpStack.h \
		FileLoaderInterface.h \
		FileIteratorInterface.h \
		FileItem.h \
		ConfigException.h \
		FileFactory.h \
		PttManager.h \
		PttAdapter.h \
		IPttListener.h \
		UDPCommunicator.h \
		TCPCommunicator.h \
		WavWriter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o TransportAdapter.o TransportAdapter.cpp

UDPCommunicator.o: UDPCommunicator.cpp UDPCommunicator.h \
		Utility.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o UDPCommunicator.o UDPCommunicator.cpp

Utility.o: Utility.cpp Utility.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Utility.o Utility.cpp

WavWriter.o: WavWriter.cpp WavWriter.h \
		Codecs.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o WavWriter.o WavWriter.cpp

Plotter.o: Plotter.cpp Plotter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Plotter.o Plotter.cpp

moc_SoftPhone.o: moc_SoftPhone.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_SoftPhone.o moc_SoftPhone.cpp

moc_Plotter.o: moc_Plotter.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_Plotter.o moc_Plotter.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

